In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn import svm
from sklearn.metrics import f1_score
#from sklearn.metrics import score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
%matplotlib inline

In [11]:
data = pd.read_csv('dataset_final.csv')
data.head(4)

IP_add  URL_length  Shortening_serv  having_at_symbol  double_slash  \
0      -1           1                1                 1            -1   
1       1           1                1                 1             1   
2       1           0                1                 1             1   
3       1           0                1                 1             1   

   prefix_suffix  sub_domain  ssl_final state  domain_reg_len  Favicon  ...  \
0             -1          -1               -1              -1        1  ...   
1             -1           0                1              -1        1  ...   
2             -1          -1               -1              -1        1  ...   
3             -1          -1               -1               1        1  ...   

   popup window  iframe  age of domain  dns record  we trffc  page rank  \
0             1       1             -1          -1        -1         -1   
1             1       1             -1          -1         0         -1   
2             1       1              1          -1         1         -1   
3             1       1             -1          -1         1         -1   

   google index  links pointing to page  statistical report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  

[4 rows x 31 columns]

In [ ]:
data.info()

In [ ]:
#sns.countplot(x='Result',data=data)

In [12]:
X = data.drop('Result',axis=1).values
y = data['Result'].values

In [16]:

classifier = svm.SVC(gamma='auto', kernel='rbf',degree =2)
classifier.fit(X,y)
accuracy_scores_2 = 100*cross_val_score(classifier, X, y, cv=5)
#f1_scores_2 = cross_val_score(classifier, X, y, cv=5, scoring='f1_macro')
#print(accuracy_scores_2)
#print(f1_scores_2)
print(np.mean(accuracy_scores_2))
#print(np.mean(f1_scores_2))

94.15638700178769


In [5]:
classifier = svm.SVC(gamma='auto', kernel='rbf',degree =2)
classifier.fit(X,y)
accuracy_scores_2 = 100*cross_val_score(classifier, X, y, cv=5)
f1_scores_2 = cross_val_score(classifier, X, y, cv=5, scoring='f1_macro')
print(accuracy_scores_2)
print(f1_scores_2)
print(np.mean(accuracy_scores_2))
print(np.mean(f1_scores_2))

[93.80650995 94.62025316 95.07010403 93.4841629  93.80090498]
[0.93684866 0.94535799 0.94988581 0.93353383 0.93689992]
94.15638700178769
0.9405052439113962


In [46]:

test_data = pd.read_csv('1phish.csv')
test_data.head()


IP_add  URL_length  Shortening_serv  having_at_symbol  double_slash  \
0      -1           1                1                 1             1   
1       1           0               -1                 1             1   
2       1           1                1                 1             1   
3       1           1               -1                 1             1   
4       1           0                1                 1             1   

   prefix_suffix  sub_domain  ssl_final state(1,0,-1)  domain_reg_len  \
0              1           1                       -1              -1   
1             -1           1                       -1              -1   
2             -1           0                       -1               1   
3              1          -1                       -1              -1   
4             -1           0                       -1               1   

   Favicon  ...  right click(1,-1)  popup window(1,-1)  Iframe(1,-1)  \
0       -1  ...                  1                  -1             1   
1        1  ...                  1                   1             1   
2        1  ...                  1                   1             1   
3        1  ...                  1                   1             1   
4        1  ...                  1                   1             1   

   age of domain(1,-1)  dns record(1,-1)  we trffc(1,0,-1)  page rank(1,-1)  \
0                    1                 1                 0                1   
1                    1                -1                 1                1   
2                   -1                 1                 1                1   
3                    1                -1                 1               -1   
4                   -1                 1                -1               -1   

   google index(1,-1)  links pointing to page(1,0,-1)  \
0                   1                               1   
1                   1                               0   
2                   1                              -1   
3                   1                              -1   
4                   1                               0   

   statistical report(1,-1)  
0                        -1  
1                         1  
2                        -1  
3                         1  
4                        -1  

[5 rows x 30 columns]

In [47]:

predictions = classifier.predict(test_data)
print(predictions)

[-1 -1 -1 -1 -1 -1  1]


In [ ]:
#filtered out phishing instances. 

In [ ]:
#fileterd out values in each column to figure out value with least number of occurence
#histogram for each features

In [ ]:
#code bruteforce attack

In [ ]:
#replace the values in phishing instances with those found above and check the prediction