In [1]:
import torch

In [9]:
#activation function - sigmoid
def activation(x):
    return 1/(1+torch.exp(-x))

In [2]:
#Data generation
torch.manual_seed(5) # setting seed value so that the result of torch.randn(n) is reproducible
matrix = torch.randn(1,5)
weight = torch.randn_like(matrix)
bias = torch.randn((1,1))

In [6]:
#weight.view(1,4)

In [8]:
h = (torch.sum(matrix*weight))+bias

In [10]:
nn = activation(h)

In [11]:
print(nn)

tensor([[0.5908]])


In [13]:
y = activation(torch.mm(matrix, weight.view(5,1)) + bias)
print(y)

tensor([[0.5908]])


In [ ]:
#################with multiple layer##################

In [28]:
torch.manual_seed(7)
matrix = torch.randn(1,3)

##defining the input, hidden and output units
input_unit = matrix.shape[1] ###here 7
#print(input_unit)
hidden_unit = 2
output_unit = 1

##defining weights
w1 = torch.randn(input_unit,hidden_unit)
w2 = torch.randn(hidden_unit, output_unit)
print(w1)
print(w2)
print(weight.shape)

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
torch.Size([1, 5])


In [29]:
###defining bias
b1 = torch.randn((1, hidden_unit))
b2 = torch.randn((1, output_unit))
print(b1)
print(b2)

tensor([[0.1328, 0.1373]])
tensor([[0.2405]])


In [30]:
###computing
h1 = activation(torch.mm(matrix,w1)+b1)
nn = activation(torch.mm(h1,w2)+b2)

print(nn)

tensor([[0.3171]])


In [ ]:
######5 layers

In [31]:
torch.manual_seed(7)
matrix = torch.randn(1,3)

##defining the input, hidden and output units
input_unit = matrix.shape[1] ###here 5
#print(input_unit)
hidden_unit = 5
output_unit = 1

##defining weights
w1 = torch.randn(input_unit,hidden_unit)
w2 = torch.randn(hidden_unit, output_unit)
print(w1)
print(w2)
print(weight.shape)

tensor([[-1.1143,  1.6908, -0.8948, -0.3556,  1.2324],
        [ 0.1382, -1.6822,  0.3177,  0.1328,  0.1373],
        [ 0.2405,  1.3955,  1.3470,  2.4382,  0.2028]])
tensor([[ 2.4505],
        [ 2.0256],
        [ 1.7792],
        [-0.9179],
        [-0.4578]])
torch.Size([1, 5])


In [32]:
b1 = torch.randn((1, hidden_unit))
b2 = torch.randn((1, output_unit))

In [33]:
h1 = activation(torch.mm(matrix,w1)+b1)
nn = activation(torch.mm(h1,w2)+b2)

print(nn)

tensor([[0.9865]])
